language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- true
before_install:
- openssl aes-256-cbc -K $encrypted_16a521bf2d15_key -iv $encrypted_16a521bf2d15_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
add_ons:
  ssh_known_hosts: 101.132.135.239
after_success:
- ssh root@101.132.135.239
- cd /srv/iSeat_BackEnd
- git pull origin master
