"""empty message

Revision ID: 8f59794865d1
Revises: 
Create Date: 2019-02-24 20:26:38.460293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f59794865d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('ch1', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('ch2', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('ch3', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('ch4', sa.String(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'name', 'type', 'ch1', 'ch2', 'ch3', 'ch4')
    )
    op.add_column('users', sa.Column('passwd', sa.String(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               autoincrement=False)
    op.drop_column('users', 'passwd')
    op.drop_table('tables')
    # ### end Alembic commands ###
